### ISSUE TITLE
RepoSense crashes too late if there are 0 valid locations in `--repo` argument

### ISSUE THREAD

**Issue by anubh-v** [reposense/RepoSense#1129]
To replicate, run the command:
`./gradlew run -Dargs="--repo abc.git"`

Output:
```
01:51:34 - [WARNING] abc.git is an invalid location.
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:372)
        at java.base/java.util.ArrayList.get(ArrayList.java:458)
        at reposense.report.ReportGenerator.cloneAndAnalyzeRepos(ReportGenerator.java:153)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:98)
        at reposense.RepoSense.main(RepoSense.java:69)
```

As seen in the stack trace, RepoSense tries to proceed with report generation even though there are no valid repo locations.

Expected: RepoSense should not proceed with report generation if there are no valid locations.

To solve: Check that there is at least one valid location

**Comment by Tejas2805** [comment]
So the **too late** is more of a location thing than a time thing?

**Comment by Tejas2805** [comment]
Working on something related to this in #905 will solve this issue in the same.

**Comment by Tejas2805** [comment]
Actually, how about making this a first-timer issue?

**Comment by anubh-v** [comment]
>So the too late is more of a location thing than a time thing?

I guess it's more of a "logic thing"  ?
The report generation should not be triggered if there isn't a single valid repo location.

 > Actually, how about making this a first-timer issue?

Sure
