### ISSUE TITLE
Older Git versions failing functional tests

### ISSUE THREAD

**Issue by yamidark** [reposense/RepoSense#127]
Older `Git` versions, such as `2.8.1`, may give different results for the `git blame` or `git log` command, such as attributing a line contribution to different authors. 

This may result in the output files produced to be inconsistent with the 'expected' results for our functional test which uses the latest `Git` version. This may confuse new developers who are still using older versions of `Git` as to why they are failing the functional tests, even if they have set up the program correctly.

Let's update the User and Developer Guide to mention that the `Git` version should be >= 2.14, and add a note that older versions may produce different results than expected.

**Comment by eugenepeh** [comment]
@yong24s , are you able to reproduce this error as well?

**Comment by yamidark** [comment]
[diff results for B1](https://github.com/reposense/RepoSense/files/2039347/result.txt)
[diff results for B2](https://github.com/reposense/RepoSense/files/2039348/result2.txt)
[diff results for summary](https://github.com/reposense/RepoSense/files/2039349/summary.txt)

**Comment by yong24s** [comment]
@eugenepeh I'll dockerize two containers for testing.

**Comment by yong24s** [comment]
So far, I got a container with git version 2.7.4 and it failed json compare.

Haven't got another container with git version 2.17.0 up yet.

**Comment by ongspxm** [comment]
lolz. Is it means you must slowly up the git version until can pass? Maybe
2.8.x can pass

**Comment by yong24s** [comment]
I got other exception.

```
> Task :functional

reposense.Entry > test STANDARD_OUT
    cloning CS2103AUG2017-W09-B1/main...
    cloning done!
    analyzing authorship...

reposense.Entry > test STANDARD_ERROR
    java.io.FileNotFoundException: repos/CS2103AUG2017-W09-B1/main/docs/LearningOutcomes.adoc (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileReader.<init>(FileReader.java:72)
        at reposense.analyzer.FileAnalyzer.isReused(FileAnalyzer.java:82)
        at reposense.analyzer.FileAnalyzer.processFiles(FileAnalyzer.java:50)
        at reposense.analyzer.FileAnalyzer.analyzeAllFiles(FileAnalyzer.java:24)
        at reposense.analyzer.RepoAnalyzer.analyzeAuthorship(RepoAnalyzer.java:23)
        at reposense.report.RepoInfoFileGenerator.generateReposReport(RepoInfoFileGenerator.java:39)
        at reposense.Entry.generateReport(Entry.java:40)
        at reposense.Entry.test(Entry.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
    java.io.FileNotFoundException: repos/CS2103AUG2017-W09-B1/main/docs/LearningOutcomes.adoc (No such file or directory)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileReader.<init>(FileReader.java:72)
        at reposense.analyzer.FileInfoGenerator.generateFileInfo(FileInfoGenerator.java:17)
        at reposense.analyzer.FileAnalyzer.processFiles(FileAnalyzer.java:53)
        at reposense.analyzer.FileAnalyzer.analyzeAllFiles(FileAnalyzer.java:24)
        at reposense.analyzer.RepoAnalyzer.analyzeAuthorship(RepoAnalyzer.java:23)
        at reposense.report.RepoInfoFileGenerator.generateReposReport(RepoInfoFileGenerator.java:39)
        at reposense.Entry.generateReport(Entry.java:40)
        at reposense.Entry.test(Entry.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:106)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
        at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
        at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:66)
        at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
        at com.sun.proxy.$Proxy1.processTestClass(Unknown Source)
        at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:109)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:155)
        at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:137)
        at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)

reposense.Entry > test FAILED
    java.lang.RuntimeException at Entry.java:40

1 test completed, 1 failed

> Task :functional FAILED

FAILURE: Build failed with an exception.

```

**Comment by yong24s** [comment]
@eugenepeh @yamidark 

Let me know if you want to run the docker containers, I can provide install and run scripts.

The following tests are tested with this Dockfile with **openjdk-8-jdk**.

> **openjdk-8-jdk** was used as it can be installed silently. 
If we intend to use docker for testing then I will figure how to install oraclejdk9 on it.

#### Dockerfile
```
FROM ubuntu:16.04

RUN apt-get update 

RUN apt-get install software-properties-common -y
RUN apt-get install openjdk-8-jdk -y

### The repo in 16.04 comes with git version 2.7.4
### Uncomment the following two lines to add repo access to install git version 2.17.0

#RUN add-apt-repository ppa:git-core/ppa -y
#RUN apt-get update
RUN apt-get install git -y

RUN git clone https://github.com/reposense/RepoSense.git /root/RepoSense

ENV PWD /root/RepoSense/
WORKDIR /root/RepoSense/
RUN ["/root/RepoSense/gradlew", "clean"]
RUN ["/root/RepoSense/gradlew", "build"]
RUN ["/root/RepoSense/gradlew", "functional", "-i"]
```


#### Output on Git 2.7.4

```
> Task :functional
Task ':functional' is not up-to-date because:
  No history is available.
Starting process 'Gradle Test Executor 1'. Working directory: /root/RepoSense Command: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager -Dorg.gradle.native=false -Dfile.encoding=UTF-8 -Duser.country=US -Duser.language=en -Duser.variant -ea -cp /root/.gradle/caches/4.7/workerMain/gradle-worker.jar worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test Executor 1'
Successfully started process 'Gradle Test Executor 1'

reposense.Entry > test STANDARD_OUT
    cloning CS2103AUG2017-W09-B1/main...
    cloning done!
    analyzing authorship...
    analyzing commits for CS2103AUG2017-W09-B1/main...
    Report for CS2103AUG2017-W09-B1_main Generated!
    cloning CS2103AUG2017-W09-B2/main...
    cloning done!
    analyzing authorship...
    analyzing commits for CS2103AUG2017-W09-B2/main...
    Report for CS2103AUG2017-W09-B2_main Generated!
    Comparing files /root/RepoSense/build/resources/functional/expected/CS2103AUG2017-W09-B2_main/commits.json & ft_temp/2018-05-26-05-18-41/CS2103AUG2017-W09-B2_main/commits.json

    Content different at line number 351:
    <<         "insertions": 745,
    >>         "insertions": 798,


Gradle Test Executor 1 finished executing tests.

> Task :functional FAILED

reposense.Entry > test FAILED
    java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at reposense.Entry.assertJson(Entry.java:61)
        at reposense.Entry.verifyAllJson(Entry.java:52)
        at reposense.Entry.verifyAllJson(Entry.java:46)
        at reposense.Entry.test(Entry.java:28)

1 test completed, 1 failed
Finished generating test XML results (0.01 secs) into: /root/RepoSense/build/test-results/functional
Generating HTML test report...
Finished generating test html results (0.029 secs) into: /root/RepoSense/build/reports/tests/functional
:functional (Thread[Task worker for ':',5,main]) completed. Took 3 mins 13.92 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':functional'.
> There were failing tests. See the report at: file:///root/RepoSense/build/reports/tests/functional/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 19s
8 actionable tasks: 2 executed, 6 up-to-date

```

#### Output on Git 2.17.0
````
> Task :functional
Finished generating test XML results (0.009 secs) into: /root/RepoSense/build/test-results/functional
Generating HTML test report...
Finished generating test html results (0.028 secs) into: /root/RepoSense/build/reports/tests/functional
:functional (Thread[Daemon worker,5,main]) completed. Took 5 mins 16.769 secs.

BUILD SUCCESSFUL in 5m 21s
8 actionable tasks: 2 executed, 6 up-to-date
````

**Comment by eugenepeh** [comment]
Ok, in that case let's just put it into the user guide. Also, make sure to configure travis to run our recommended version in the ci test.
