### ISSUE TITLE
ArrayIndexOutOfBoundsException generating report with RepoSense 

### ISSUE THREAD

**Issue by chan-j-d** [reposense/RepoSense#1636]
**Tell us about your environment**

* **RepoSense Version:** master branch
* **OS and Version:** Windows 10
* **Web Browser and Version (if applicable):**

**Please include the steps to reproduce the bug.**

1. Run `java -jar RepoSense.jar --repos https://github.com/AY2021S1-CS2103-F09-1/tp.git --since 01/06/2020 --view`

**What was expected to happen?**
Report generated and displayed without issue.

**What actually happened? Please include a screenshot of the output.**
Report was not generated. 
![image](https://user-images.githubusercontent.com/65345505/151711457-02a2e049-dd32-4dd7-8d7d-69f4003a3cdf.png)
Full error message that shows up while processing
```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at reposense.authorship.FileInfoAnalyzer.generateBinaryFileResult(FileInfoAnalyzer.java:125)
        at reposense.authorship.FileInfoAnalyzer.analyzeBinaryFile(FileInfoAnalyzer.java:91)
        at reposense.authorship.AuthorshipReporter.lambda$generateAuthorshipSummary$2(AuthorshipReporter.java:51)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at reposense.authorship.AuthorshipReporter.generateAuthorshipSummary(AuthorshipReporter.java:53)
        at reposense.report.ReportGenerator.analyzeRepo(ReportGenerator.java:374)
        at reposense.report.ReportGenerator.analyzeRepos(ReportGenerator.java:327)
        at reposense.report.ReportGenerator.lambda$cloneAndAnalyzeRepos$1(ReportGenerator.java:237)
        at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
        at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**If possible, include the URL to your RepoSense report or log files (if any).**
[log.txt](https://github.com/reposense/RepoSense/files/7966549/log.txt)

**Comment by chan-j-d** [comment]
Running on Ubuntu 18.04 gives a different error message but also caused by `FileInfoAnalyzer::generateBinaryFileResult`. There might be more info such as the specific command ran so I am sharing the additional log file as well.

[ubuntu-log.txt](https://github.com/reposense/RepoSense/files/7966568/ubuntu-log.txt)

**Comment by damithc** [comment]
Let's investigate to figure out what's going on and how serious this bug is.

**Comment by chan-j-d** [comment]
It seems like for Linux systems, the file in question is an image file with path ending with `../$Remark.png` which causes bash to attempt to replace it with a value as evidenced by `docs/images/add-remark/.png` showing up in the log. 

However, Windows command prompt does not seem to treat the '$' as a special character so I'm still unsure why there is an exception.

**Comment by chan-j-d** [comment]
It seems there are two separate bugs for these two issues. The main problem causing the issue in this post is that some commits do not have an email tagged to them. Most commits show up something like this
![image](https://user-images.githubusercontent.com/65345505/153696868-562e5e2c-9c7c-4879-aacb-ca6a3bfadf76.png)
even if I selected my email setting as private, there is still a dummy email address. 

However, there is one specific commit in that repository ([link here](https://github.com/AY2021S1-CS2103-F09-1/tp/commit/86f65cc7058472c96caee9d853580af9134670c8)) where `git show` shows this:
![image](https://user-images.githubusercontent.com/65345505/153696981-8e9b7129-154d-4063-b21d-7b6fe4643275.png). 
Thus, during the split in the code below

https://github.com/reposense/RepoSense/blob/728a9f9c14f706ace6873cae8696647b91ff3ffb/src/main/java/reposense/authorship/FileInfoAnalyzer.java#L122-L127

The array only has one entry which is the author name without an address causing the exception. 

The issue with running git commands on bash with special characters is placed in a separate issue here.
