### ISSUE TITLE
FileInfoAnalyzer#isReused throws MalformedInputException while generating report for CS2103JAN2018-T11-B1/main

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#182]
```
INFO: Extracting commits info for CS2103JAN2018-T11-B1/main...
Jul 12, 2018 5:06:40 PM reposense.authorship.FileInfoExtractor extractFileInfos
INFO: Extracting relevant file infos...
Jul 12, 2018 5:07:59 PM reposense.authorship.FileInfoAnalyzer isReused
WARNING: Input length = 1
java.nio.charset.MalformedInputException: Input length = 1
	at java.nio.charset.CoderResult.throwException(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.read1(Unknown Source)
	at java.io.BufferedReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at reposense.authorship.FileInfoAnalyzer.isReused(FileInfoAnalyzer.java:102)
	at reposense.authorship.FileInfoAnalyzer.analyzeFile(FileInfoAnalyzer.java:40)
	at reposense.authorship.AuthorshipReporter.lambda$generateAuthorshipSummary$0(AuthorshipReporter.java:24)
	at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.collect(Unknown Source)
	at reposense.authorship.AuthorshipReporter.generateAuthorshipSummary(AuthorshipReporter.java:26)
	at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:45)
	at reposense.RepoSense.main(RepoSense.java:31)

**Comment by yamidark** [comment]
>Can you try using a different buffer size and see if it helps? 

The error occurs when we are using `BufferedReader` to read line by line, and there is no way to define a buffer for it.
The [`MalformedInputException`](https://docs.oracle.com/javase/8/docs/api/java/nio/charset/MalformedInputException.html) is due to having characters with invalid byte sequence according to the `Charset` used, and [`Files.newBufferedReader(Path)`](https://docs.oracle.com/javase/8/docs/api/java/nio/file/Files.html#newBufferedReader-java.nio.file.Path-) uses `UTF-8` by default.

**Comment by yamidark** [comment]
Based on this [SO](https://stackoverflow.com/questions/26268132/all-inclusive-charset-to-avoid-java-nio-charset-malformedinputexception-input) post, we can resolve this by using `java.io.File` style `new BufferedReader(new InputStreamReader(File)))` instead of `java.nio.Files` style `Files.newBufferedReader(Path)`.
This is due to `Files.newBufferedReader(Path)` using the default `CharsetDecoder`, which will throw the error by default, of any `Charset` we may provide:
```java
    public static BufferedReader newBufferedReader(Path path, Charset cs)
        throws IOException
    {
        CharsetDecoder decoder = cs.newDecoder();
        Reader reader = new InputStreamReader(newInputStream(path), decoder);
        return new BufferedReader(reader);
    }
```
while `new InputStreamReader(File)` will set the `CharsetDecoder` to 'replace' the 'MalformedInput' instead of throwing an error:
```java
 StreamDecoder(InputStream var1, Object var2, Charset var3) {
        this(var1, var2, var3.newDecoder().onMalformedInput(CodingErrorAction.REPLACE).onUnmappableCharacter(CodingErrorAction.REPLACE));
    }
```
This was also why v1.0 was able to generate the dashboard correctly before we switch from `java.io.File` to `java.nio.Path`.

**Comment by eugenepeh** [comment]
>@eugenepeh Should we just switch back to old BufferedReader style for now?

I am okay if that's the easiest and most efficient way to resolve the problem.

**Comment by yong24s** [comment]
The following are the repos that failed with the same error
- CS2103JAN2018-T11-B1/main
- CS2103JAN2018-W11-B2/main
- CS2103JAN2018-W11-B4/main

**Comment by yong24s** [comment]
Agreed. 

```BufferedReader#newBufferedReader``` is just a wrapper function; its implementation of using ```CharsetDecoder decoder = cs.newDecoder();``` doesn't allow us to customize the decoder behavior. 

So let's just construct a reader directly with ```Reader reader = new InputStreamReader(newInputStream(path), decoder);```
