### ISSUE TITLE
Gson parsing exception. 

### ISSUE THREAD

**Issue by quackerjeff** [reposense/RepoSense#2051]
### Tell us about your environment
Latest RepoSense
Both Linux and MacOS
### Please include the steps to reproduce the bug.
Just running it against a repository the Gson parser fails 

### What actually happened? Please include a screenshot of the output.
Exception in thread "main" com.google.gson.JsonIOException: Failed making field 'java.time.ZoneRegion#id' accessible; either change its visibility or write a custom TypeAdapter for its declaring type
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:22)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
	at com.google.gson.Gson.getAdapter(Gson.java:501)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
	at com.google.gson.Gson.toJson(Gson.java:747)
	at com.google.gson.Gson.toJson(Gson.java:726)
	at com.google.gson.Gson.toJson(Gson.java:681)
	at com.google.gson.Gson.toJson(Gson.java:661)
	at reposense.util.FileUtil.writeJsonFile(FileUtil.java:117)
	at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:135)
	at reposense.RepoSense.main(RepoSense.java:84)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.time.ZoneRegion.id accessible: module java.base does not "opens java.time" to unnamed module @5eb06f3f
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:180)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:174)
	at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:19)

**Comment by jq1836** [comment]
Hi there @quackerjeff, firstly, thanks for pointing this bug out. Would just like to get more details regarding your environment, specifically, your Java version, as we have an existing bug report #1944, that relates to a similar/same problem.

In addition to this, could I also request for the log file which can be found in the `reposense-report/reposense-logs` directory, along with the manner of which the program was used, i.e. through CLI, GitHub actions, etc. Also, information regarding the CLI arguments used would be much appreciated.

In the mean time, if you do require urgent use of RepoSense, do try running the program with Java 8 onwards, excluding Java 17, as it seems from our investigation in #1944 that the problem is caused by using RepoSense with Java 17 onwards.

**Comment by supermii2** [comment]
Hi there, I've managed to replicate the issue with Java 17, and as jq mentioned it works fine on Java 8.

`~/Documents/jars$ java -jar RepoSense.jar --repos https://github.com/reposense/RepoSense.git --view
10:37:54 - Log temp folder has been successfully created
10:37:55 - Cloning in parallel from https://github.com/reposense/RepoSense.git...
10:37:55 - Waiting for cloning of https://github.com/reposense/RepoSense.git to complete...
10:38:05 - Cloning of https://github.com/reposense/RepoSense.git completed!
10:38:05 - [1/1] Analyzing https://github.com/reposense/RepoSense.git (master)...
10:38:05 - Extracting relevant file info from https://github.com/reposense/RepoSense.git (master)...
10:38:06 - Extracting commits info for https://github.com/reposense/RepoSense.git (master)...
10:38:06 - Analyzing commits info for https://github.com/reposense/RepoSense.git (master)...
10:38:06 - Analysis of https://github.com/reposense/RepoSense.git (master) completed!
Exception in thread "main" com.google.gson.JsonIOException: Failed making field 'java.time.ZoneRegion#id' accessible; either change its visibility or write a custom TypeAdapter for its declaring type
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:22)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.getBoundFields(ReflectiveTypeAdapterFactory.java:158)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory.create(ReflectiveTypeAdapterFactory.java:101)
        at com.google.gson.Gson.getAdapter(Gson.java:501)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.write(TypeAdapterRuntimeTypeWrapper.java:56)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.write(ReflectiveTypeAdapterFactory.java:126)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.write(ReflectiveTypeAdapterFactory.java:244)
        at com.google.gson.Gson.toJson(Gson.java:747)
        at com.google.gson.Gson.toJson(Gson.java:726)
        at com.google.gson.Gson.toJson(Gson.java:681)
        at com.google.gson.Gson.toJson(Gson.java:661)
        at reposense.util.FileUtil.writeJsonFile(FileUtil.java:117)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:135)
        at reposense.RepoSense.main(RepoSense.java:84)
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field private final java.lang.String java.time.ZoneRegion.id accessible: module java.base does not "opens java.time" to unnamed module @5a6d67c3
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:178)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:172)
        at com.google.gson.internal.reflect.ReflectionHelper.makeAccessible(ReflectionHelper.java:19)
        ... 13 more`

**Comment by supermii2** [comment]
Closed due to likely using the wrong version of java
