### ISSUE TITLE
To investigate: Travis-CI (Linux)/Gradlew may fail on CI on a rare occasion 

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#237]
Fails on Travis Linux.
```
Unzipping /home/travis/.gradle/wrapper/dists/gradle-4.7-all/4cret0dgl5o3b21weaoncl7ys/gradle-4.7-all.zip to /home/travis/.gradle/wrapper/dists/gradle-4.7-all/4cret0dgl5o3b21weaoncl7ys
Exception in thread "main" java.util.zip.ZipException: zip END header not found
	at java.base/java.util.zip.ZipFile$Source.zerror(ZipFile.java:1252)
	at java.base/java.util.zip.ZipFile$Source.findEND(ZipFile.java:1153)
	at java.base/java.util.zip.ZipFile$Source.initCEN(ZipFile.java:1160)
	at java.base/java.util.zip.ZipFile$Source.<init>(ZipFile.java:997)
	at java.base/java.util.zip.ZipFile$Source.get(ZipFile.java:960)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:216)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:148)
	at java.base/java.util.zip.ZipFile.<init>(ZipFile.java:162)
	at org.gradle.wrapper.Install.unzip(Install.java:215)
	at org.gradle.wrapper.Install.access$600(Install.java:27)
	at org.gradle.wrapper.Install$1.call(Install.java:75)
	at org.gradle.wrapper.Install$1.call(Install.java:48)
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:69)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:107)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
```

**Comment by eugenepeh** [comment]
I don't think this belongs to our problem? It seems like it occurs when gradle unzipping its own package.

**Comment by yamidark** [comment]
>One way to rectify is to remove the following block in .travis.yml and add it back later.

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

I don't think this resolves the problem (for my case at least).
Rather, what resolved for my PR was by deleting the cache on Travis [here](https://travis-ci.org/reposense/RepoSense/caches).
Extra note, my PR continuously failed on Travis had a slightly lesser cache size then the others (at 220MB compared to 222MB of the rest), probably means it missed downloading some files (in my case, was from `.jar` file?).
