### ISSUE TITLE
error matching file path pattern inside file diff result

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#299]
v1.2.1

Relevant config lines:

Repository's   Location | Branch | Author's GitHub ID | Author's Display Name | Author's Git Author Name | Ignore Glob List
-- | -- | -- | -- | -- | --
https://github.com/se-edu/se-book.git | master | damithc | Damith | Damith C.   Rajapakse
https://github.com/nus-cs2103/website-base.git | master | damithc | Damith | Damith C. Rajapakse

Error:
04:49:46 - Failed to match the file path group for:
similarity index 100%
rename from admin/project-testing.md
rename to admin/project-testing.fr
Exception in thread "main" java.lang.AssertionError: Should not have error matching file path pattern inside file diff result!
        at reposense.authorship.FileInfoExtractor.getFilePathFromDiffPattern(FileInfoExtractor.java:210)
        at reposense.authorship.FileInfoExtractor.getEditedFileInfos(FileInfoExtractor.java:99)
        at reposense.authorship.FileInfoExtractor.extractFileInfos(FileInfoExtractor.java:67)
        at reposense.authorship.AuthorshipReporter.generateAuthorshipSummary(AuthorshipReporter.java:21)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:63)
        at reposense.RepoSense.main(RepoSense.java:51)

**Comment by damithc** [comment]
I was stress testing RS using my own github data when I ran into this issue. Is it a known problem that has been fixed in the next version?

**Comment by yamidark** [comment]
@damithc 

May I know the date range used for this?
I believe this is the same problem as specified in #215, where there is no `diff` between the files within the date range, just this time it is a file rename instead of creating a new file.

**Comment by damithc** [comment]
`-since 19/05/2018`
