### ISSUE TITLE
Allow non-alpha-numeric characters in GitHub usernames

### ISSUE THREAD

**Issue by damithc** [reposense/RepoSense#340]
Error message:
```
12:41:22 - CS2103-AY1819S1-W10-2_main_master has no authors specified, using all authors by default.
Exception in thread "main" java.lang.IllegalArgumentException: The provided Git ID, Aiden Low (Yew Woei), contains illegal characters.
        at reposense.model.Author.<init>(Author.java:35)
        at reposense.git.GitShortlog.lambda$extractAuthorsFromLog$0(GitShortlog.java:24)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at reposense.git.GitShortlog.extractAuthorsFromLog(GitShortlog.java:26)
        at reposense.report.ReportGenerator.updateAuthorList(ReportGenerator.java:112)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:66)
        at reposense.RepoSense.main(RepoSense.java:51)

```

**Comment by damithc** [comment]
Here's another case:
```
$ java -jar RepoSense.jar -repo https://github.com/damithc/markdown-here.git
09:34:02 - Cloning https://github.com/damithc/markdown-here.git...
09:34:13 - Cloning completed!
09:34:14 - damithc_markdown-here_master has no authors specified, using all authors by default.
Exception in thread "main" java.lang.IllegalArgumentException: The provided Git ID, DarÃ­o HereÃ±Ãº, contains illegal characters.
        at reposense.model.Author.<init>(Author.java:35)
        at reposense.git.GitShortlog.lambda$extractAuthorsFromLog$0(GitShortlog.java:24)
        at java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Unknown Source)
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
        at java.util.stream.ReferencePipeline.collect(Unknown Source)
        at reposense.git.GitShortlog.extractAuthorsFromLog(GitShortlog.java:26)
        at reposense.report.ReportGenerator.updateAuthorList(ReportGenerator.java:112)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:66)
        at reposense.RepoSense.main(RepoSense.java:51)
```

**Comment by damithc** [comment]
Looks like the problem extends to Git author names as well.
```
Exception in thread "main" java.lang.IllegalArgumentException: The provided author alias, Adam Pritchard <pritchard.adam@gmail.com>, contains illegal characters.
        at reposense.model.Author.validateAuthorAliases(Author.java:94)
        at reposense.model.Author.<init>(Author.java:57)
        at reposense.model.RepoConfiguration.update(RepoConfiguration.java:152)
        at reposense.report.ReportGenerator.updateRepoConfig(ReportGenerator.java:95)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:65)
        at reposense.RepoSense.main(RepoSense.java:51)
```
