### ISSUE TITLE
Invalid file path leads to unhandled exception in Git Log

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#398]
```11:00:19 - Extracting commits info for https://github.com/CS2113-AY1819S1-F10-1/main.git...
Exception in thread "main" java.lang.RuntimeException: Error returned from command git log --no-merges -i  --since="2018-09-12T00:00:00+08:00" --pretty=format:"%H|%aN|%ad|%s" --date=iso --shortstat --author="^meisbokai <.*>$\|^Neow Bo Kai <.*>$\|^meisbokai <.*>$" -- "*.adoc" -- "*.cs" -- "*.css" -- "*.fxml" -- "*.gradle" -- "*.html" -- "*.java" -- "*.js" -- "*.json" -- "*.jsp" -- "*.md" -- "*.py" -- "*.tag" -- "*.xml" ":(exclude)*.class" ":(exclude)addressbook.txt" ":(exclude)backup_data.txt" ":(exclude)exams.txt" ":(exclude)statistics.txt" ":(exclude)*.jar" ":(exclude)*.war" ":(exclude)*.ear" ":(exclude).idea/" ":(exclude)*.iml" ":(exclude)out/" ":(exclude)/bin/" ":(exclude)/data/" ":(exclude)publish.sh" ":(exclude).gradle/" ":(exclude)build/"on path repos\main\main :
fatal: Invalid path '/bin': No such file or directory

        at reposense.system.CommandRunner.runCommand(CommandRunner.java:169)
        at reposense.system.CommandRunner.gitLog(CommandRunner.java:38)
        at reposense.commits.CommitInfoExtractor.extractCommitInfos(CommitInfoExtractor.java:32)
        at reposense.commits.CommitsReporter.generateCommitSummary(CommitsReporter.java:19)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:71)
        at reposense.RepoSense.main(RepoSense.java:51)```

**Comment by chelseyong** [comment]
@eugenepeh can I clarify the current problem with this?

**Comment by eugenepeh** [comment]
>Edit: The issue seems to exist when non-existing folder is inside ignore-glob-list.

Yes, thats indeed the case. In one of my old PR, I've tried to resolve this problem by changing the
`:(exclude)/bin/` to `:!/bin/`. It manage to subdue this problem however it was unexplainable why. Perhaps you would like to continue that lead and try to fix this problem.

However if that does not solve the issue completely, can look to do a directory check prior to using the glob list. Or if you found better solution while researching on this problem, can propose to implement it as well.

**Comment by yamidark** [comment]
@eugenepeh 

>Yes, thats indeed the case. In one of my old PR, I've tried to resolve this problem by changing the
:(exclude)/bin/ to :!/bin/. It manage to subdue this problem however it was unexplainable why. Perhaps you would like to continue that lead and try to fix this problem.

I believe I gave an explanation for this, where the `:` at the front may consume some 'magic' characters after it, like the `!` and `/`, causing `git log` to take the relative directory `bin/` as the glob value instead (can't remember where I or you posted this somewhere). This probably won't work for Windows OS which has the drive letter (`C:` `D:`) at the front instead.

@chelseyong 
>The issue seems to exist when non-existing folder is inside ignore-glob-list.

Not exactly, it is possible to give a non-existing folder/directory relative to the git repository, and it will not give an error (just nothing to ignore there).
Rather, the error comes when we try to add a filepath which is **outside** of the git repository, like giving an absolutely filepath instead. So you will need some way to detecting if the given glob may possibly point to outside of the git directory (giving absolutely filepath, or traversing to parent of the git repository first with `../`)
![untitled](https://user-images.githubusercontent.com/18352498/53970151-0ab1b000-4135-11e9-9f67-e03314c699bc.png)

**Comment by eugenepeh** [comment]
>I believe I gave an explanation for this, where the : at the front may consume some 'magic' characters after it, like the ! and /

Yes, I think we discussed this over slack. I don't remember we reached a conclusion about this though because end of the day, no documentation was found. For example, what kind of magic characters would get consumed and the resultant effect.

**Comment by yamidark** [comment]
The documentation for the git pathspec magic can be found [here](https://git-scm.com/docs/gitglossary#gitglossary-aiddefpathspecapathspec), for your reference if needed.
