### ISSUE TITLE
Make StandaloneConfig foolproof from NullPointerException

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#402]
```Exception in thread "main" java.lang.NullPointerException
        at reposense.model.Author.<init>(Author.java:34)
        at reposense.model.RepoConfiguration.update(RepoConfiguration.java:152)
        at reposense.report.ReportGenerator.updateRepoConfig(ReportGenerator.java:98)
        at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:68)
        at reposense.RepoSense.main(RepoSense.java:51)

```
![image](https://user-images.githubusercontent.com/19277206/48393937-833ace00-e74c-11e8-829d-25f86d574949.png)

When the a json list is terminated with a `,`, it introduce an additional null element to the list when we load it back as a java object. This leads to an unhandled NullPointerException. To prevent this from happening, we should make the StandaloneConfig class fool proof from such configuration errors.

**Comment by yong24s** [comment]
According to https://github.com/google/gson/issues/494, gson intends to fix trailing commas in version 3.0. 

While it is easy to circumvent trailing commas in lists i.e. `[one, two,]` by removing null elements, but for maps `{one, two,}` an exception will be thrown.

Let's pre-process the config file and remove trailing commas as it is simpler than changing json dependencies.
