### ISSUE TITLE
GitBlame: RuntimeError when analyzing branch name that is within whitelisted format

### ISSUE THREAD

**Issue by yamidark** [reposense/RepoSense#508]
```
Exception in thread "main" java.lang.RuntimeException: Error returned from command git blame -w --line-porcelain ".git/logs/refs/heads/haha.txt"on path repos/testrepo-Charlie/testrepo-Charlie :
fatal: no such path '.git/logs/refs/heads/haha.txt' in HEAD

    at reposense.system.CommandRunner.runCommand(CommandRunner.java:55)
    at reposense.git.GitBlame.blame(GitBlame.java:32)
    at reposense.authorship.FileInfoAnalyzer.getGitBlameResult(FileInfoAnalyzer.java:107)
    at reposense.authorship.FileInfoAnalyzer.aggregateBlameAuthorInfo(FileInfoAnalyzer.java:82)
    at reposense.authorship.FileInfoAnalyzer.analyzeFile(FileInfoAnalyzer.java:48)
    at reposense.authorship.AuthorshipReporter.lambda$generateAuthorshipSummary$0(AuthorshipReporter.java:24)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1492)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at reposense.authorship.AuthorshipReporter.generateAuthorshipSummary(AuthorshipReporter.java:26)
    at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:78)
    at reposense.RepoSense.main(RepoSense.java:52)
```

To replicate, create a branch and name it with a file extension being analyzed (e.g. `xxx.txt`), and in that branch create a file of the same name, and run the analysis.

**Comment by emer7** [comment]
It is not necessary to create a file of the same name with the branch to trigger the error.
My finding so far is that creating a branch name that fulfills file format white-list will trigger the error because of the file in `.git/refs/heads/<branch name that fulfills file format white-list>`

**Comment by eugenepeh** [comment]
Do update the issue and pr title accordingly
