### ISSUE TITLE
DashboardServer: Desktop#isDesktopSupported passes on headless systems

### ISSUE THREAD

**Issue by yong24s** [reposense/RepoSense#561]
https://github.com/reposense/RepoSense/blob/2c6b44ac323008c3c2b55789fee9c2f014c2f879/src/main/java/reposense/system/DashboardServer.java#L48-L50

```
> Task :startServerInBackground
** (java:5160): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Exception in thread "main" java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
    at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:380)
    at java.desktop/java.awt.Desktop.browse(Desktop.java:524)
    at reposense.system.DashboardServer.launchBrowser(DashboardServer.java:49)
    at reposense.system.DashboardServer.startServer(DashboardServer.java:36)
    at reposense.RepoSense.main(RepoSense.java:59)
```

**Comment by yong24s** [comment]
```
static boolean isDesktopSupported()
Tests whether this class is supported on the current platform.

boolean isSupported(Desktop.Action action)
Tests whether an action is supported on the current platform.
```
Should use `isSupported(Desktop.Action.BROWSE)`

https://docs.oracle.com/javase/7/docs/api/java/awt/Desktop.html

Putting as **P.Medium** since it doesn't break CI. 🤔
