### ISSUE TITLE
FrontendTest: Cypress fails occasionally on master branch

### ISSUE THREAD

**Issue by eugenepeh** [reposense/RepoSense#594]
```
 code view
    ✓ at first start shows tutorial message (888ms)
    1) can be closed
  1 passing (10s)
  1 failing
  1) code view can be closed:
     CypressError: Timed out retrying: Expected to find element: '#tabs-wrapper', but never found it.
      at Object.cypressErr (http://localhost:9000/__cypress/runner/cypress_runner.js:65283:11)
      at Object.throwErr (http://localhost:9000/__cypress/runner/cypress_runner.js:65248:18)
      at Object.throwErrByPath (http://localhost:9000/__cypress/runner/cypress_runner.js:65275:17)
      at retry (http://localhost:9000/__cypress/runner/cypress_runner.js:58816:16)
      at http://localhost:9000/__cypress/runner/cypress_runner.js:50924:18
      at tryCatcher (http://localhost:9000/__cypress/runner/cypress_runner.js:127195:23)
      at Promise._settlePromiseFromHandler (http://localhost:9000/__cypress/runner/cypress_runner.js:125213:31)
      at Promise._settlePromise (http://localhost:9000/__cypress/runner/cypress_runner.js:125270:18)
      at Promise._settlePromise0 (http://localhost:9000/__cypress/runner/cypress_runner.js:125315:10)
      at Promise._settlePromises (http://localhost:9000/__cypress/runner/cypress_runner.js:125390:18)
      at Async._drainQueue (http://localhost:9000/__cypress/runner/cypress_runner.js:122119:16)
      at Async._drainQueues (http://localhost:9000/__cypress/runner/cypress_runner.js:122129:10)
      at Async.drainQueues (http://localhost:9000/__cypress/runner/cypress_runner.js:122003:14)
```

**Comment by eugenepeh** [comment]
duplicate of #584
