### ISSUE TITLE
Weird log message that displays report location of a certain repo with no reason for the error

### ISSUE THREAD

**Issue by jylee-git** [reposense/RepoSense#825]
Parameters used: `-c ./ -s d1 -v`

Weird line of log is displayed as error: 
```
10:13:35 - [ERROR] C:\Users\jylee\Documents\repos\RepoSense\reposense-report\reposense\testrepo-Alpha[master]
```
, located at the 4th last line of the log below.

The full log is displayed below.

```
10:11:48 - Cloning in parallel from https://github.com/reposense/testrepo-Delta.git...
10:11:48 - Waiting for cloning of https://github.com/reposense/testrepo-Delta.git to complete...
10:11:54 - Cloning of https://github.com/reposense/testrepo-Delta.git completed!
10:12:00 - Cloning in parallel from https://github.com/reposense/RepoSense.git...
10:12:00 - Analyzing https://github.com/reposense/testrepo-Delta.git (master)...
10:12:01 - Extracting commits info for https://github.com/reposense/testrepo-Delta.git (master)...
10:12:02 - Analyzing commits info for https://github.com/reposense/testrepo-Delta.git (master)...
10:12:02 - Extracting relevant file info from https://github.com/reposense/testrepo-Delta.git (master)...
10:12:41 - Analysis of https://github.com/reposense/testrepo-Delta.git (master) completed!
10:12:41 - Analyzing https://github.com/reposense/testrepo-Delta.git (nonExistentBranch)...
10:12:41 - [ERROR] Branch nonExistentBranch does not exist in https://github.com/reposense/testrepo-Delta.git! Analysis terminated.
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.gson.internal.reflect.UnsafeReflectionAccessor (file:/C:/Users/jylee/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.5/f645ed69d595b24d4cf8b3fbb64cc505bede8829/gson-2.8.5.jar) to constructor java.util.Collections$EmptyList()
WARNING: Please consider reporting this to the maintainers of com.google.gson.internal.reflect.UnsafeReflectionAccessor
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
10:12:41 - Waiting for cloning of https://github.com/reposense/RepoSense.git to complete...
10:12:41 - Cloning of https://github.com/reposense/RepoSense.git completed!
10:12:46 - Cloning in parallel from https://github.com/reposense/testrepo-Alpha.git...
10:12:46 - Analyzing https://github.com/reposense/RepoSense.git (master)...
10:12:46 - Extracting commits info for https://github.com/reposense/RepoSense.git (master)...
10:12:47 - Analyzing commits info for https://github.com/reposense/RepoSense.git (master)...
10:12:47 - Extracting relevant file info from https://github.com/reposense/RepoSense.git (master)...
10:13:02 - Analysis of https://github.com/reposense/RepoSense.git (master) completed!
10:13:02 - Waiting for cloning of https://github.com/reposense/testrepo-Alpha.git to complete...
10:13:02 - Cloning of https://github.com/reposense/testrepo-Alpha.git completed!
reposense.git.exception.GitCloneException: reposense.system.CommandRunnerProcessException: Error returned from command git ls-tree --name-only -r masteron path repos\reposense_testrepo-Empty\testrepo-Empty :
fatal: Not a valid object name master

	at reposense.git.GitLsTree.validateFilePaths(GitLsTree.java:54)
	at reposense.report.RepoCloner.spawnCloneProcess(RepoCloner.java:104)
	at reposense.report.RepoCloner.clone(RepoCloner.java:56)
	at reposense.report.ReportGenerator.cloneAndAnalyzeRepos(ReportGenerator.java:128)
	at reposense.report.ReportGenerator.generateReposReport(ReportGenerator.java:82)
	at reposense.RepoSense.main(RepoSense.java:61)
10:13:04 - Analyzing https://github.com/reposense/testrepo-Alpha.git (master)...
10:13:04 - [WARNING] The provided commit hash, , contains illegal characters. Ignoring the config provided by https://github.com/reposense/testrepo-Alpha.git (master).
10:13:04 - https://github.com/reposense/testrepo-Alpha.git (master) has no authors specified, using all authors by default.
10:13:04 - Extracting commits info for https://github.com/reposense/testrepo-Alpha.git (master)...
10:13:05 - Analyzing commits info for https://github.com/reposense/testrepo-Alpha.git (master)...
10:13:05 - Extracting relevant file info from https://github.com/reposense/testrepo-Alpha.git (master)...
10:13:06 - Analysis of https://github.com/reposense/testrepo-Alpha.git (master) completed!
10:13:06 - Waiting for cloning of https://github.com/reposense/testrepo-Empty.git to complete...
10:13:06 - [WARNING] Exception met while trying to clone the repo, will skip this repo.
10:13:14 - Cloning in parallel from https://github.com/reposense/testrepo-Beta.git...
10:13:14 - Waiting for cloning of https://github.com/reposense/testrepo-Beta.git to complete...
10:13:26 - Cloning of https://github.com/reposense/testrepo-Beta.git completed!
10:13:27 - Analyzing https://github.com/reposense/testrepo-Beta.git (master)...
10:13:27 - Ignoring standalone config file in https://github.com/reposense/testrepo-Beta.git (master).
10:13:27 - Extracting commits info for https://github.com/reposense/testrepo-Beta.git (master)...
10:13:28 - Analyzing commits info for https://github.com/reposense/testrepo-Beta.git (master)...
10:13:28 - Extracting relevant file info from https://github.com/reposense/testrepo-Beta.git (master)...
10:13:31 - Analysis of https://github.com/reposense/testrepo-Beta.git (master) completed!
10:13:31 - Analyzing https://github.com/reposense/testrepo-Beta.git (add-config-json)...
10:13:31 - Ignoring standalone config file in https://github.com/reposense/testrepo-Beta.git (add-config-json).
10:13:31 - Extracting commits info for https://github.com/reposense/testrepo-Beta.git (add-config-json)...
10:13:32 - Analyzing commits info for https://github.com/reposense/testrepo-Beta.git (add-config-json)...
10:13:32 - Extracting relevant file info from https://github.com/reposense/testrepo-Beta.git (add-config-json)...
10:13:35 - Analysis of https://github.com/reposense/testrepo-Beta.git (add-config-json) completed!
10:13:35 - The report is generated at C:\Users\jylee\Documents\repos\RepoSense\reposense-report
10:13:35 - [ERROR] C:\Users\jylee\Documents\repos\RepoSense\reposense-report\reposense\testrepo-Alpha[master]
10:13:35 - Starting a server at port 9000...
10:13:35 - Loading http://localhost:9000/ on the default browser...
10:13:35 - Press Ctrl + C or equivalent to stop the server

```

**Comment by fzdy1914** [comment]
May related to the GitCloneExeception

**Comment by jylee-git** [comment]
Found out why. This is caused by #802 as a result of changing the display name of the repos report, that led to the failure to ZIP the required files. Hence the weird exception.
